#!/bin/csh

# modules loaded (Pleiades)
#
# module load comp-intel/2013.5.192
# module load mpi-sgi/mpt.2.10r6

setenv CC mpiicc
setenv FC mpiifort
setenv CFLAGS "-O3"
setenv FCFLAGS "-O3"

./configure --without-pthread --disable-shared --enable-parallel --enable-production --enable-fortran --enable-fortran2003 --disable-stream-vfd --disable-direct-vfd --with-zlib=${HOME}/packages/zlib-1.2.8/lib --prefix=${HOME}/packages/phdf5-1_8
make
make install