
!include ..\make.win

WRITE  = $(OUTDIR)\cgwrite.exe
READ   = $(OUTDIR)\cgread.exe
MODIFY = $(OUTDIR)\cgmodify.exe
DELETE = $(OUTDIR)\cgdelete.exe

all    : write read modify delete
write  : $(OUTDIR) $(WRITE)
read   : $(OUTDIR) $(READ)
modify : $(OUTDIR) $(MODIFY)
delete : $(OUTDIR) $(DELETE)

test  : write read
	-@del Test_V2
	$(WRITE)
	$(READ) > $(OUTDIR)\output
	-$(DIFF) OUTPUT $(OUTDIR)\output

$(OUTDIR) :
	-mkdir $(OUTDIR)

$(WRITE)  : cgwrite.F
$(READ)   : cgread.F
$(MODIFY) : cgmodify.F
$(DELETE) : cgdelete.F

clean :
	-del Test_V2
	-del /q $(OUTDIR)\*.*
	-rmdir $(OUTDIR)

